### ISSUE TITLE
Error when opening index

### ISSUE THREAD

**Issue by drfurtado** [garthtarr/sydney_xaringan#7]
I have followed the instructions to clone this repo, which is awesome btw.

But I am getting the following error when knit the index file.

```
Quitting from lines 40-86 (index.Rmd) 
Error in icon_find(name, "fontawesome")[[1]] : subscript out of bounds
Calls: <Anonymous> ... eval -> eval -> top_icon -> <Anonymous> -> <Anonymous>
Execution halted
```
Any help is appreciated.

**Comment by garthtarr** [comment]
I think the issue is that installing the `icons` package isn't enough, you also need to initialise the fontawesome library:

```r
icons::download_fontawesome()
```

**Comment by drfurtado** [comment]
It did the trick. Thanks for putting this together; very useful.
